### ISSUE TITLE
The steam workshop addon is down.

### ISSUE THREAD

**Issue by Purpling** [ZeroNoFun/Gmod-Aperture-science-laboratories#20]
I hope this is not permanent, but if it is I will reupload it to the steam workshop with permission.

![image](https://user-images.githubusercontent.com/28204565/49347053-5cf4b800-f692-11e8-8f89-4979a56bf948.png)
![image](https://user-images.githubusercontent.com/28204565/49347068-6e3dc480-f692-11e8-947a-5bd7ab17c28c.png)

I did some looking and found this at the wayback machine:
https://web.archive.org/web/20170901072653/https://steamcommunity.com/sharedfiles/filedetails/?id=862644776

I also have the original files uploaded to my dropbox:
https://www.dropbox.com/s/hdkc9vvjkak83vu/the_aperture_862644776.gma?dl=0

**Comment by ZeroNoFun** [comment]
As CrishNate said - "I'v decided to shutown it. Because it have too much issues, and I can't fix them since I left gmod modding.
The addon only will stay on the GitHub, so that if people need it, they can have it.
(if any questions left, you are free to add me)"

So... any mod creators now have full permission to rewrite/edit this addon and release it on gmod workshop.
